# -*- coding: utf-8 -*-
"""
Dados-semente dos playbooks de resposta a incidentes.
Cada passo de fase é um dicionário {"text": ..., "tools": [...]} em vez de uma
string simples, para que a resolução aponte para ferramentas concretas de
segurança e de rede/infraestrutura de TI usadas para a executar.
"""

def s(text, tools=None):
    return {"text": text, "tools": tools or []}


PRIORITY_INFO = {
    "P1": {"label": "P1 · Crítica", "response": "Imediata · < 15 min", "authority": "CISO / Comité de Crise",
           "desc": "Impacto severo em CID (confidencialidade, integridade, disponibilidade); risco à continuidade de negócio ou obrigação legal imediata (RGPD/NIS2)."},
    "P2": {"label": "P2 · Alta", "response": "< 30 min", "authority": "SOC Lead / Responsável de Segurança",
           "desc": "Impacto significativo, mas contido a um sistema, conta ou processo; sem risco iminente à continuidade de negócio."},
    "P3": {"label": "P3 · Média", "response": "< 1 hora", "authority": "Analista SOC sénior",
           "desc": "Impacto limitado a um único ativo ou utilizador; tratável dentro do horário normal de operação."},
    "P4": {"label": "P4 · Baixa", "response": "< 4h ou turno seguinte", "authority": "Analista SOC",
           "desc": "Impacto mínimo, tipicamente de custo ou eficiência; sem exposição de dados nem indisponibilidade de serviço."},
}

CATEGORIES = [
    {
        "id": "malware", "name": "Ataques de Malware e Ransomware", "color": "var(--cat-malware)", "icon": "bug",
        "playbooks": [
            {
                "id": "ransomware", "icon": "lock", "name": "Ransomware", "severity": "critical",
                "sla": "Ativação < 15 min",
                "team": ["SOC", "IT Infraestrutura", "Network", "Backup & DR", "Direção / Comité de Crise", "Jurídico"],
                "detectionMethods": ["EDR/XDR (deteção de encriptação em massa)", "SIEM — correlação de eventos",
                                      "Monitorização de integridade de backups", "Honeyfiles / canary files",
                                      "Alertas de deceção (deception tech)"],
                "priority": "P1",
                "attack": [{"id": "T1486", "name": "Data Encrypted for Impact"}, {"id": "T1490", "name": "Inhibit System Recovery"}],
                "related": ["exfiltracao", "credenciais", "invasao-rede"],
                "objective": "Conter a propagação de ransomware, preservar evidência forense e restaurar operações a partir de backups íntegros sem pagar resgate nem reencriptar dados já comprometidos.",
                "indicators": ["Extensões de ficheiro alteradas em massa", "Notas de resgate (readme/decrypt.txt)",
                               "Picos de I/O em disco", "Serviços de backup desativados", "Ligações a domínios .onion"],
                "containment": [
                    s("Isolar imediatamente os sistemas afetados da rede (desligar Wi-Fi/cabo, não desligar a máquina)",
                      ["EDR/XDR (CrowdStrike Falcon, Microsoft Defender for Endpoint, SentinelOne) — isolamento de host com 1 clique",
                       "NAC (Cisco ISE, Aruba ClearPass, ForeScout) — quarentena automática de porta/VLAN"]),
                    s("Desativar contas de serviço e partilhas de rede associadas aos hosts comprometidos",
                      ["Active Directory / PowerShell (Disable-ADAccount, módulo ActiveDirectory)",
                       "Microsoft Entra ID / Okta — suspensão de conta e revogação de sessão"]),
                    s("Bloquear os IOCs conhecidos (hashes, IPs C2, domínios) em firewall/EDR",
                      ["NGFW (Palo Alto Panorama, Fortinet FortiGate, Cisco Firepower)",
                       "EDR/XDR — bloqueio de hash/IOC em toda a frota",
                       "DNS Security / RPZ (Cisco Umbrella, Infoblox)"]),
                    s("Identificar o vetor inicial (email, RDP exposto, VPN, supply chain)",
                      ["SIEM (Splunk, Microsoft Sentinel, IBM QRadar)", "Secure Email Gateway (Proofpoint, Mimecast)",
                       "Scanner de exposição externa (Shodan, Censys, Tenable.io)"]),
                    s("Preservar uma cópia forense (disco/memória) antes de qualquer remediação",
                      ["Velociraptor, KAPE, FTK Imager — aquisição forense", "Ferramenta de memory dump (WinPMEM, Magnet RAM Capture)"]),
                ],
                "eradication": [
                    s("Identificar a variante de ransomware e correlacionar com inteligência de ameaças",
                      ["ID Ransomware / No More Ransom", "Threat Intel (Recorded Future, MISP, VirusTotal)"]),
                    s("Analisar exfiltração de dados prévia à encriptação (dupla extorsão)",
                      ["DLP (Microsoft Purview, Forcepoint)", "Análise de logs de proxy/firewall (NetFlow)", "CASB (Defender for Cloud Apps, Netskope)"]),
                    s("Remover persistência, tarefas agendadas e contas criadas pelo atacante",
                      ["EDR/XDR — remediação automática", "PowerShell / Sysinternals Autoruns", "Active Directory — auditoria de contas e GPOs"]),
                    s("Repor credenciais de todas as contas com privilégios nos sistemas afetados",
                      ["PAM (CyberArk, BeyondTrust, HashiCorp Vault)", "Active Directory — reset em massa + krbtgt se necessário"]),
                ],
                "recovery": [
                    s("Validar integridade e ausência de reinfeção nos backups antes de restaurar",
                      ["Veeam, Commvault, Rubrik, Veritas NetBackup — verificação de imutabilidade e scan antimalware do backup"]),
                    s("Restaurar por ordem de criticidade de negócio, em ambiente segmentado",
                      ["Backup & DR (Veeam Instant Recovery, Rubrik)", "Rede — VLANs de quarentena / sandbox de restauro"]),
                    s("Reconstruir hosts a partir de imagem limpa sempre que a limpeza não seja garantida",
                      ["Imagem dourada (SCCM, Intune, MDT/Autopilot)", "Ferramenta de deployment (FOG, Clonezilla para on-prem)"]),
                    s("Monitorizar intensivamente 30 dias após restauro",
                      ["EDR/XDR — modo de vigilância reforçada", "SIEM — regras de deteção dedicadas ao IOC do incidente"]),
                ],
                "communication": [
                    s("Ativar plano de continuidade de negócio e comité de crise", ["Ferramenta de gestão de crise/BCP (Everbridge, Noggin)"]),
                    s("RGPD: se houver dados pessoais expostos, notificar a CNPD em até 72h e avaliar comunicação aos titulares (risco elevado)"),
                    s("NIS2: se a organização for entidade essencial/importante, emitir alerta precoce ao CNCS em 24h, notificação em 72h e relatório final em 1 mês"),
                    s("Preparar comunicação interna e, se aplicável, externa (clientes, reguladores, seguradora de cyber-risco)"),
                    s("Não contactar nem negociar com o atacante sem aprovação legal/direção"),
                ],
                "postIncident": [
                    s("Relatório de causa raiz e linha temporal completa do ataque", ["Timeline builder (TheHive, DFIR-ORC, planilha de IR)"]),
                    s("Rever política de backups (regra 3-2-1, imutabilidade, isolamento offline)", ["Backup imutável (Veeam Hardened Repository, S3 Object Lock)"]),
                    s("Reforçar segmentação de rede e privilégio mínimo", ["Microsegmentação (Illumio, Cisco ACI, NSX)", "Active Directory Tiering Model"]),
                ],
            },
            {
                "id": "malware-comum", "icon": "bug", "name": "Malware Comum / Infeção por Vírus", "severity": "high",
                "sla": "Ativação < 30 min",
                "team": ["SOC", "Helpdesk / Suporte IT", "Network"],
                "detectionMethods": ["Antivírus / EDR", "SIEM — correlação de alertas de endpoint", "Sandbox de análise de amostras"],
                "priority": "P3",
                "attack": [{"id": "T1204", "name": "User Execution"}, {"id": "T1059", "name": "Command and Scripting Interpreter"}],
                "related": ["ransomware", "criptojacking"],
                "objective": "Conter e remover infeções de malware em endpoints individuais antes de escalarem para movimento lateral, preservando amostras para análise.",
                "indicators": ["Alertas de antivírus/EDR", "Processos desconhecidos com ligações de rede suspeitas",
                               "Degradação de performance do endpoint", "Alterações não autorizadas em chaves de arranque"],
                "containment": [
                    s("Isolar o endpoint afetado da rede via EDR ou desconexão física",
                      ["EDR/XDR (Defender for Endpoint, CrowdStrike, SentinelOne) — isolamento de rede remoto"]),
                    s("Recolher amostra do ficheiro malicioso em ambiente controlado (sandbox)",
                      ["Any.Run, Joe Sandbox, Cuckoo Sandbox", "VirusTotal (upload privado)"]),
                    s("Identificar processos e conexões de rede associados ao malware",
                      ["Sysinternals (Process Explorer, TCPView)", "EDR — árvore de processos e telemetria de rede"]),
                    s("Bloquear hash e indicadores em toda a frota via EDR/antivírus",
                      ["EDR/XDR — bloqueio global de hash/IOC", "Gestão centralizada de antivírus (Defender ATP, ESET PROTECT)"]),
                ],
                "eradication": [
                    s("Eliminar ficheiros, chaves de registo e tarefas agendadas maliciosas",
                      ["EDR — remediação guiada", "Sysinternals Autoruns", "PowerShell remoto (Invoke-Command)"]),
                    s("Executar scan completo com motores atualizados", ["Antivírus corporativo + motor offline (Microsoft Safety Scanner, ESET Online Scanner)"]),
                    s("Verificar se existem mecanismos de persistência adicionais (serviços, drivers)",
                      ["Sysinternals Autoruns/Process Monitor", "EDR — deteção de driver não assinado"]),
                ],
                "recovery": [
                    s("Reintegrar o endpoint na rede apenas após scan limpo confirmado", ["EDR — relatório de compliance do dispositivo", "NAC — reavaliação de postura antes de reconectar"]),
                    s("Repor palavra-passe do utilizador do dispositivo afetado", ["Active Directory / Entra ID — reset forçado"]),
                    s("Monitorizar o endpoint durante 7 dias", ["EDR — watchlist dedicada"]),
                ],
                "communication": [
                    s("Informar o utilizador afetado e recolher contexto (email aberto, USB, download)"),
                    s("Notificar a equipa de segurança se o mesmo hash aparecer noutros hosts", ["SIEM — pesquisa retroativa do IOC em toda a frota"]),
                ],
                "postIncident": [
                    s("Atualizar assinaturas/regras de deteção com o novo IOC", ["SIEM/EDR — custom IOC rules", "Threat Intel Platform (MISP)"]),
                    s("Reforçar formação de sensibilização se a origem for phishing", ["Plataforma de simulação de phishing (KnowBe4, Proofpoint Security Awareness)"]),
                ],
            },
            {
                "id": "criptojacking", "icon": "cpu", "name": "Criptojacking / Mineração Não Autorizada", "severity": "medium",
                "sla": "Ativação < 1h",
                "team": ["SOC", "Infraestrutura / Cloud Ops", "Network", "FinOps"],
                "detectionMethods": ["Monitorização de CPU/GPU (thresholds)", "Alertas de anomalia de custo cloud (FinOps)",
                                      "Monitorização de DNS/proxy para pools de mineração"],
                "priority": "P4",
                "attack": [{"id": "T1496", "name": "Resource Hijacking"}],
                "related": ["malware-comum", "cloud-misconfig"],
                "objective": "Detetar e eliminar processos de mineração de criptomoeda não autorizados, cortando o acesso às pools de mineração e restaurando capacidade de processamento.",
                "indicators": ["Uso sustentado de CPU/GPU próximo de 100%", "Ventoinhas/temperatura anómalas em servidores",
                               "Tráfego de rede para pools de mineração conhecidas", "Contentores ou tarefas cron desconhecidas"],
                "containment": [
                    s("Identificar hosts com picos anómalos de CPU/GPU via monitorização",
                      ["Monitorização de infraestrutura (Zabbix, Datadog, Prometheus/Grafana)", "Cloud cost anomaly detection (AWS Cost Anomaly, Azure Cost Management)"]),
                    s("Encerrar processos de mineração não autorizados", ["EDR/XDR", "SSH + kill manual em servidores Linux", "Kubernetes — eliminação de pod (kubectl delete pod)"]),
                    s("Bloquear domínios e portas de pools de mineração conhecidas na firewall",
                      ["NGFW (Palo Alto, Fortinet)", "DNS Security (Cisco Umbrella, Infoblox)"]),
                    s("Isolar temporariamente o host se o processo resistir a terminação", ["EDR — isolamento de rede", "Hypervisor — suspensão de VM (VMware vCenter, Hyper-V)"]),
                ],
                "eradication": [
                    s("Localizar e remover binários, scripts cron e contentores maliciosos",
                      ["Linux: crontab -l / systemd timers", "Container security (Aqua Security, Trivy, Prisma Cloud)"]),
                    s("Identificar vulnerabilidade ou credencial que permitiu a execução (RCE, credenciais fracas, imagem de container comprometida)",
                      ["Vulnerability management (Tenable Nessus, Qualys, Rapid7 InsightVM)", "Image scanning (Trivy, Grype)"]),
                    s("Corrigir a vulnerabilidade explorada", ["Gestor de patches (WSUS, Intune, Ansible)"]),
                ],
                "recovery": [
                    s("Repor performance normal do sistema e validar ausência de recorrência", ["Monitorização de infraestrutura — baseline de CPU/GPU"]),
                    s("Reforçar hardening de imagens de contentores e patch de vulnerabilidades exploradas", ["CIS Benchmarks / Docker Bench for Security"]),
                ],
                "communication": [
                    s("Reportar impacto em custos de infraestrutura/cloud à gestão", ["Relatório FinOps (AWS Cost Explorer, Azure Cost Management)"]),
                    s("Documentar vetor de entrada para revisão de arquitetura"),
                ],
                "postIncident": [
                    s("Implementar alertas automáticos de uso anómalo de CPU/GPU", ["Datadog/Grafana — alerting", "Cloud provider budget alerts"]),
                    s("Rever políticas de execução de contentores e permissões de imagem", ["Kubernetes — Pod Security Standards, OPA/Gatekeeper"]),
                ],
            },
        ],
    },
    {
        "id": "social", "name": "Engenharia Social e Identidade", "color": "var(--cat-social)", "icon": "users",
        "playbooks": [
            {
                "id": "phishing", "icon": "mail", "name": "Phishing", "severity": "high", "sla": "Ativação < 30 min",
                "team": ["SOC", "Segurança de Email", "Comunicação Interna", "Network"],
                "detectionMethods": ["Reportes de utilizadores (botão de phishing)", "Secure Email Gateway (SEG)", "SIEM — correlação de indicadores"],
                "priority": "P2",
                "attack": [{"id": "T1566", "name": "Phishing"}, {"id": "T1204.001", "name": "Malicious Link"}],
                "related": ["credenciais", "bec", "malware-comum"],
                "objective": "Neutralizar campanhas de phishing removendo o email de todas as caixas, bloqueando a infraestrutura maliciosa e protegendo as contas de utilizadores que interagiram com a mensagem.",
                "indicators": ["Reportes de utilizadores via botão de phishing", "Remetente falsificado (spoofing)",
                               "URLs encurtados ou com typosquatting", "Anexos com macros ou executáveis"],
                "containment": [
                    s("Bloquear o remetente e o domínio malicioso no gateway de email",
                      ["Secure Email Gateway (Proofpoint, Mimecast, Microsoft Defender for Office 365)"]),
                    s("Remover o email de todas as caixas de correio (purge retroativo)",
                      ["Microsoft 365 Defender / Exchange — Threat Explorer + Purge", "Google Workspace Security Center"]),
                    s("Bloquear os URLs maliciosos no proxy/DNS/firewall", ["Proxy web (Zscaler, Forcepoint)", "DNS Security (Cisco Umbrella)"]),
                    s("Identificar todos os destinatários e utilizadores que clicaram/introduziram credenciais",
                      ["SEG — relatório de entrega/clique", "SIEM — correlação de logs de proxy"]),
                ],
                "eradication": [
                    s("Rotacionar credenciais de todos os utilizadores que introduziram dados na página falsa", ["Entra ID / Active Directory — reset em massa + revogação de sessão"]),
                    s("Rever regras de encaminhamento de email criadas após o incidente", ["PowerShell Exchange Online (Get-InboxRule)", "Microsoft 365 Defender — auditoria de regras"]),
                    s("Analisar o URL/anexo em sandbox para extrair IOCs adicionais", ["Any.Run, Joe Sandbox, urlscan.io"]),
                ],
                "recovery": [
                    s("Encerrar sessões ativas e forçar novo login com MFA nas contas afetadas", ["Entra ID / Okta — revoke sessions + MFA challenge"]),
                    s("Confirmar ausência de atividade fraudulenta nas contas comprometidas", ["SIEM/UEBA — revisão de atividade pós-incidente"]),
                ],
                "communication": [
                    s("Emitir alerta interno a todos os colaboradores sobre a campanha", ["Plataforma de comunicação interna (Teams, intranet)"]),
                    s("Reportar o domínio/URL a listas de bloqueio e, se aplicável, ao registrar", ["Google Safe Browsing / Microsoft SmartScreen submission"]),
                ],
                "postIncident": [
                    s("Atualizar filtros anti-phishing com os novos indicadores", ["SEG — regras customizadas", "MISP — partilha de IOCs"]),
                    s("Incluir o caso em formação de sensibilização (simulações de phishing)", ["KnowBe4, Proofpoint Security Awareness Training"]),
                ],
            },
            {
                "id": "bec", "icon": "briefcase", "name": "Business Email Compromise (BEC)", "severity": "critical",
                "sla": "Ativação < 15 min",
                "team": ["SOC", "Financeiro", "Jurídico", "Direção", "Network"],
                "detectionMethods": ["Deteção de anomalias no email (regras/reencaminhamentos)", "SIEM — geolocalização de login", "Alertas antifraude do banco"],
                "priority": "P1",
                "attack": [{"id": "T1566", "name": "Phishing"}, {"id": "T1114.003", "name": "Email Forwarding Rule"}, {"id": "T1078", "name": "Valid Accounts"}],
                "related": ["phishing", "credenciais"],
                "objective": "Interromper fraude financeira baseada em comprometimento de email corporativo, recuperar fundos desviados quando possível e eliminar o acesso do atacante à caixa de correio.",
                "indicators": ["Pedidos urgentes e fora do padrão para alterar dados bancários", "Regras de reencaminhamento ocultas na caixa de correio",
                               "Login a partir de geolocalização/IP invulgar", "Domínios semelhantes ao da organização (lookalike)"],
                "containment": [
                    s("Suspender imediatamente a conta de email comprometida e encerrar todas as sessões",
                      ["Entra ID / Google Workspace Admin — suspend user + revoke sessions"]),
                    s("Contactar o banco para tentar reter/reverter a transferência (SWIFT recall)", ["Portal bancário / linha direta de fraude do banco emissor"]),
                    s("Revogar tokens OAuth e aplicações de terceiros ligadas à conta", ["Entra ID Enterprise Apps / Google Workspace — revoke OAuth grants"]),
                    s("Identificar e remover regras de reencaminhamento e delegação de acesso",
                      ["PowerShell Exchange Online (Get-InboxRule, Remove-InboxRule)", "Microsoft 365 Defender — auditoria de delegação"]),
                ],
                "eradication": [
                    s("Investigar o vetor inicial (phishing, credential stuffing, MFA fatigue)", ["SIEM — correlação de logs de autenticação", "Entra ID Sign-in logs"]),
                    s("Rever logs de auditoria do email (login, alterações de regras, downloads)", ["Microsoft Purview Audit / Unified Audit Log"]),
                    s("Verificar se outras contas partilham padrão de comprometimento", ["UEBA (Microsoft Defender for Cloud Apps, Exabeam)"]),
                ],
                "recovery": [
                    s("Repor credenciais e reforçar MFA resistente a phishing (FIDO2)", ["Entra ID / Okta — chaves de segurança FIDO2, Windows Hello for Business"]),
                    s("Restaurar acesso normal apenas após validação de integridade da conta", ["Checklist de validação de identidade + aprovação de gestor"]),
                ],
                "communication": [
                    s("Envolver financeiro, jurídico e apresentar queixa junto da Polícia Judiciária (Cibercrime) por fraude financeira"),
                    s("Notificar o banco emissor e o banco recetor da transferência o mais rápido possível para tentar recall/bloqueio de fundos"),
                    s("Notificar parceiros/fornecedores que possam ter recebido instruções fraudulentas em nome da empresa"),
                    s("RGPD: avaliar exposição de dados pessoais na caixa de correio comprometida e necessidade de notificação à CNPD"),
                ],
                "postIncident": [
                    s("Implementar verificação dupla (callback telefónico) para alterações de dados bancários"),
                    s("Auditar todas as regras de encaminhamento de email na organização", ["PowerShell — auditoria em massa de Get-InboxRule em todos os mailboxes"]),
                ],
            },
            {
                "id": "credenciais", "icon": "key", "name": "Comprometimento de Credenciais", "severity": "high",
                "sla": "Ativação < 20 min",
                "team": ["SOC", "IAM / Identity Team", "Helpdesk", "Network"],
                "detectionMethods": ["Identity Protection (impossible travel)", "SIEM", "UEBA — deteção de comportamento anómalo"],
                "priority": "P2",
                "attack": [{"id": "T1078", "name": "Valid Accounts"}, {"id": "T1110", "name": "Brute Force"}],
                "related": ["phishing", "forca-bruta", "invasao-rede"],
                "objective": "Conter o uso indevido de credenciais comprometidas, cortar o acesso do atacante e restaurar o controlo legítimo da conta com autenticação reforçada.",
                "indicators": ["Alertas de impossible travel", "Login fora de horário habitual",
                               "Alteração inesperada de MFA/dados de recuperação", "Atividade em sistemas fora do perfil habitual do utilizador"],
                "containment": [
                    s("Suspender a conta imediatamente (desativar, não apagar)", ["Entra ID / Active Directory — Disable-ADAccount / suspend user"]),
                    s("Encerrar todas as sessões ativas e tokens de atualização", ["Entra ID — Revoke-AzureADUserAllRefreshToken", "Okta — clear sessions"]),
                    s("Redefinir a palavra-passe através de canal fora de banda", ["Helpdesk — verificação de identidade por telefone/vídeo antes do reset"]),
                    s("Validar e reconfigurar os métodos de MFA associados", ["Entra ID Authentication Methods / Duo / Okta Verify"]),
                ],
                "eradication": [
                    s("Rever logs de acesso para identificar ações realizadas com a conta comprometida", ["SIEM — timeline de atividade da conta", "Entra ID Sign-in & Audit logs"]),
                    s("Verificar criação de regras, chaves de API ou acessos persistentes pelo atacante", ["Cloud IAM audit (AWS CloudTrail, Azure Activity Log)"]),
                    s("Identificar a origem da fuga (reutilização de password, infostealer, phishing)", ["Dark web monitoring (Recorded Future, HaveIBeenPwned for Business)"]),
                ],
                "recovery": [
                    s("Reativar a conta apenas após confirmação de posse pelo utilizador legítimo"),
                    s("Monitorizar a conta durante o período seguinte à reativação", ["UEBA — watchlist temporária"]),
                ],
                "communication": [
                    s("Informar o utilizador sobre as ações tomadas e boas práticas (gestor de passwords)", ["Bitwarden, 1Password (recomendação corporativa)"]),
                    s("Verificar se as credenciais expostas são reutilizadas noutros sistemas", ["Dark web / breach monitoring"]),
                ],
                "postIncident": [
                    s("Verificar exposição em bases de dados de fugas conhecidas (dark web monitoring)"),
                    s("Reforçar política de MFA obrigatório e complexidade de password", ["Entra ID Conditional Access / Password Protection"]),
                ],
            },
            {
                "id": "forca-bruta", "icon": "repeat", "name": "Ataque de Força Bruta / Password Spraying", "severity": "medium",
                "sla": "Ativação < 45 min",
                "team": ["SOC", "Network", "Infraestrutura de Rede"],
                "detectionMethods": ["SIEM — correlação de falhas de login", "IDS/IPS", "WAF", "Logs do serviço de autenticação"],
                "priority": "P3",
                "attack": [{"id": "T1110", "name": "Brute Force"}, {"id": "T1110.003", "name": "Password Spraying"}],
                "related": ["credenciais", "ddos"],
                "objective": "Travar tentativas automatizadas de adivinhação de credenciais antes que resultem em comprometimento de conta, sem impor bloqueios que causem negação de serviço legítima.",
                "indicators": ["Múltiplas falhas de autenticação em curto espaço de tempo", "Falhas distribuídas por muitas contas a partir do mesmo IP (spraying)",
                               "Tentativas de login a partir de IPs/ASN de reputação baixa", "Picos de tráfego no endpoint de autenticação"],
                "containment": [
                    s("Bloquear temporariamente os IPs/intervalos de origem identificados",
                      ["NGFW (Palo Alto, Fortinet)", "IPS (Cisco Firepower, Snort/Suricata)", "Entra ID — Named Locations / Conditional Access block"]),
                    s("Aplicar bloqueio de conta após N tentativas falhadas (account lockout policy)", ["Active Directory — Account Lockout Policy (GPO)", "Entra ID — Smart Lockout"]),
                    s("Ativar MFA obrigatório para todas as contas visadas, se ainda não ativo", ["Entra ID Conditional Access / Duo"]),
                    s("Aumentar logging e alertas no serviço de autenticação durante o ataque", ["SIEM — regra temporária de alta sensibilidade"]),
                ],
                "eradication": [
                    s("Confirmar que nenhuma tentativa teve sucesso (revisão de logs de login válido)", ["SIEM / Entra ID Sign-in logs"]),
                    s("Identificar se as listas de utilizadores usadas vieram de fuga de dados anterior", ["Threat Intel / dark web monitoring"]),
                ],
                "recovery": [
                    s("Levantar bloqueios de IP após confirmação do fim da atividade maliciosa", ["NGFW / IPS — remoção de regra temporária"]),
                    s("Restaurar acesso a utilizadores legítimos afetados pelo lockout", ["Helpdesk — Unlock-ADAccount / reset assistido"]),
                ],
                "communication": [
                    s("Notificar utilizadores cujas contas foram bloqueadas por precaução"),
                    s("Reportar IPs de origem a feeds de threat intelligence partilhados", ["MISP / ISAC do setor"]),
                ],
                "postIncident": [
                    s("Implementar rate limiting e CAPTCHA adaptativo no login", ["WAF (Cloudflare, F5) — regras de rate limiting", "Azure AD B2C / Entra External ID CAPTCHA"]),
                    s("Rever política de complexidade de password e MFA obrigatório", ["Entra ID Password Protection + banned password list"]),
                ],
            },
        ],
    },
    {
        "id": "rede", "name": "Segurança de Rede e Infraestrutura", "color": "var(--cat-network)", "icon": "network",
        "playbooks": [
            {
                "id": "ddos", "icon": "waves", "name": "Ataques DDoS", "severity": "high", "sla": "Ativação < 10 min",
                "team": ["SOC", "Network", "Rede / NOC", "Provedor DDoS / CDN"],
                "detectionMethods": ["Monitorização de rede (NetFlow/sFlow)", "Alertas do serviço de proteção DDoS", "APM — deteção de degradação de serviço"],
                "priority": "P2",
                "attack": [{"id": "T1498", "name": "Network Denial of Service"}, {"id": "T1499", "name": "Endpoint Denial of Service"}],
                "related": ["forca-bruta", "web-attacks"],
                "objective": "Manter a disponibilidade dos serviços sob ataque volumétrico ou de aplicação, absorvendo ou filtrando o tráfego malicioso sem afetar utilizadores legítimos.",
                "indicators": ["Pico súbito e anómalo de tráfego de entrada", "Latência ou indisponibilidade de serviços públicos",
                               "Padrões de tráfego repetitivo de múltiplas origens (botnet)", "Esgotamento de ligações em balanceadores/firewalls"],
                "containment": [
                    s("Ativar mitigação de tráfego junto do provedor de DDoS protection / CDN", ["Cloudflare, Akamai Prolexic, AWS Shield Advanced"]),
                    s("Aplicar rate limiting nos endpoints e APIs expostos", ["WAF (Cloudflare, F5 Advanced WAF)", "API Gateway (Kong, Azure APIM) — throttling policies"]),
                    s("Bloquear em massa os IPs/ASN de origem identificados como maliciosos", ["NGFW / Router ACLs (Cisco, Juniper)", "BGP Flowspec / RTBH (Remote Triggered Black Hole)"]),
                    s("Desviar tráfego para a CDN/edge network para absorver o volume", ["Cloudflare / Akamai / AWS CloudFront — DNS failover"]),
                ],
                "eradication": [
                    s("Identificar o tipo de ataque (volumétrico, protocolo, aplicação) e ajustar regras de mitigação", ["NetFlow/sFlow analyzer (SolarWinds, ntopng)", "WAF/DDoS dashboard"]),
                    s("Colaborar com o ISP/provedor upstream para scrubbing de tráfego na origem", ["Contacto direto com NOC do ISP / scrubbing center"]),
                ],
                "recovery": [
                    s("Restabelecer níveis normais de rate limiting após confirmação do fim do ataque", ["WAF / API Gateway — reversão de políticas temporárias"]),
                    s("Validar disponibilidade e performance dos serviços afetados", ["APM (Datadog, New Relic, Dynatrace)"]),
                ],
                "communication": [
                    s("Atualizar página de estado do serviço (status page) para clientes", ["Statuspage, Atlassian Statuspage, Instatus"]),
                    s("Informar a gestão sobre impacto e duração do incidente"),
                ],
                "postIncident": [
                    s("Rever capacidade de mitigação contratada e dimensionamento de infraestrutura", ["Revisão de contrato com provedor de DDoS/CDN"]),
                    s("Documentar assinatura do ataque para deteção mais rápida no futuro", ["SIEM — regra de deteção dedicada"]),
                ],
            },
            {
                "id": "invasao-rede", "icon": "network", "name": "Invasão de Rede / Movimentação Lateral", "severity": "critical",
                "sla": "Ativação < 15 min",
                "team": ["SOC", "Threat Hunting / Red Team", "IT Infraestrutura", "Network"],
                "detectionMethods": ["EDR/XDR", "NDR — Network Detection & Response", "SIEM", "Auditoria do Active Directory"],
                "priority": "P1",
                "attack": [{"id": "T1021", "name": "Remote Services"}, {"id": "T1570", "name": "Lateral Tool Transfer"}, {"id": "T1078", "name": "Valid Accounts"}],
                "related": ["credenciais", "exfiltracao", "ransomware"],
                "objective": "Deter um atacante já dentro da rede antes que expanda o acesso a sistemas críticos, cortando as vias de movimentação lateral e revogando credenciais comprometidas.",
                "indicators": ["Uso anómalo de contas privilegiadas (ex: admin de domínio)", "Ferramentas de pentest/lateral movement não autorizadas (PsExec, Mimikatz, Cobalt Strike)",
                               "Tráfego SMB/RDP interno fora do padrão", "Novas contas ou grupos criados no Active Directory"],
                "containment": [
                    s("Isolar os segmentos de rede afetados (VLANs, microsegmentação)", ["Microsegmentação (Illumio, Cisco ACI, VMware NSX)", "NAC — quarentena de VLAN"]),
                    s("Revogar chaves SSH, tokens de API e certificados potencialmente comprometidos", ["PAM (CyberArk, HashiCorp Vault)", "PKI interna — revogação de certificados"]),
                    s("Desativar contas privilegiadas suspeitas e forçar reset de Kerberos (krbtgt se necessário)", ["Active Directory / PowerShell — reset krbtgt (2x)", "Microsoft Defender for Identity"]),
                    s("Bloquear tráfego lateral entre segmentos não essenciais", ["NGFW / East-West firewall rules", "NDR (Darktrace, ExtraHop, Vectra AI)"]),
                ],
                "eradication": [
                    s("Analisar logs de firewall, Active Directory e EDR para mapear a linha temporal completa",
                      ["SIEM (Splunk, Sentinel)", "Microsoft Defender for Identity / BloodHound (deteção de paths de ataque)"]),
                    s("Remover contas, GPOs e mecanismos de persistência criados pelo atacante", ["Active Directory — auditoria de GPOs e Scheduled Tasks", "EDR — remediação"]),
                    s("Identificar e corrigir o ponto de entrada inicial", ["Vulnerability scanner (Tenable, Qualys)"]),
                ],
                "recovery": [
                    s("Restaurar segmentação normal por fases, monitorizando cada segmento reativado", ["NDR — vigilância reforçada por segmento"]),
                    s("Repor palavra-passe de todas as contas de serviço e administrativas do domínio", ["Active Directory — reset em massa via PAM"]),
                ],
                "communication": [
                    s("Ativar equipa de resposta a incidentes e, se crítico, direção executiva"),
                    s("NIS2: avaliar se o incidente é \"significativo\" (perturbação operacional relevante ou perdas financeiras) e obriga a alerta ao CNCS em 24h"),
                    s("Avaliar necessidade de suporte forense externo especializado", ["DFIR retainer (Mandiant, CrowdStrike Services)"]),
                ],
                "postIncident": [
                    s("Implementar Tiering Model / privilégio mínimo no Active Directory", ["Microsoft Tiering Model / PAM"]),
                    s("Reforçar deteção de movimento lateral (honeytokens, alertas de comportamento)", ["Honeytokens (Thinkst Canary)", "UEBA"]),
                ],
            },
            {
                "id": "exfiltracao", "icon": "database", "name": "Exfiltração / Vazamento de Dados", "severity": "critical",
                "sla": "Ativação < 15 min",
                "team": ["SOC", "DLP Team", "Network", "Jurídico / DPO"],
                "detectionMethods": ["DLP — Data Loss Prevention", "SIEM", "CASB", "Análise de tráfego de rede"],
                "priority": "P1",
                "attack": [{"id": "T1041", "name": "Exfiltration Over C2 Channel"}, {"id": "T1567", "name": "Exfiltration Over Web Service"}],
                "related": ["ransomware", "invasao-rede", "insider-threat"],
                "objective": "Interromper a saída não autorizada de dados, quantificar o que foi exposto e cumprir as obrigações legais de notificação dentro dos prazos aplicáveis.",
                "indicators": ["Volumes de upload anómalos para destinos externos", "Acesso em massa a repositórios de dados fora do padrão do utilizador",
                               "Uso de canais não autorizados (armazenamento pessoal na cloud, USB)", "Alertas de DLP (Data Loss Prevention)"],
                "containment": [
                    s("Identificar e bloquear o canal de saída dos dados (rede, endpoint, aplicação)",
                      ["DLP (Microsoft Purview, Forcepoint, Symantec)", "CASB (Defender for Cloud Apps, Netskope)"]),
                    s("Bloquear transferências em curso e suspender contas/processos envolvidos", ["NGFW / Proxy (Zscaler)", "Entra ID — suspensão de conta"]),
                    s("Preservar evidência do tráfego e dos ficheiros acedidos/exportados", ["NDR/NetFlow capture", "Forense (Velociraptor, KAPE)"]),
                    s("Isolar o sistema de origem da exfiltração", ["EDR/XDR — isolamento de host"]),
                ],
                "eradication": [
                    s("Auditar exatamente quais dados foram expostos e a sensibilidade dos mesmos", ["DLP — relatório de classificação", "Microsoft Purview Information Protection"]),
                    s("Identificar a causa raiz (credencial comprometida, insider, vulnerabilidade aplicacional)", ["SIEM — correlação de eventos"]),
                    s("Remover o acesso ou vulnerabilidade que permitiu a exfiltração", ["IAM — revisão de permissões", "Patch management"]),
                ],
                "recovery": [
                    s("Restaurar controlos de acesso e validar que não existem canais de saída adicionais", ["CASB / DLP — varredura completa"]),
                    s("Reforçar regras de DLP para os padrões de dados identificados", ["Microsoft Purview DLP policies"]),
                ],
                "communication": [
                    s("RGPD: notificar a CNPD em até 72h após tomar conhecimento; sem demora injustificada aos titulares se o risco for elevado (Art. 33.º/34.º)"),
                    s("NIS2: se aplicável ao setor da organização, alerta precoce ao CNCS em 24h e notificação formal em 72h"),
                    s("Envolver jurídico/DPO para avaliar obrigações contratuais, setoriais e regulatórias adicionais"),
                    s("Preparar comunicação a titulares de dados e/ou clientes afetados, se aplicável"),
                ],
                "postIncident": [
                    s("Classificar e rotular dados sensíveis para melhorar deteção futura de DLP", ["Microsoft Purview Information Protection — labels de sensibilidade"]),
                    s("Rever permissões de acesso segundo o princípio do menor privilégio", ["IAM — access review (Entra ID Access Reviews)"]),
                ],
            },
        ],
    },
    {
        "id": "cloud", "name": "Segurança em Nuvem (Cloud) e Aplicações", "color": "var(--cat-cloud)", "icon": "cloud",
        "playbooks": [
            {
                "id": "web-attacks", "icon": "code", "name": "Ataques a Aplicações Web (SQLi, XSS)", "severity": "high",
                "sla": "Ativação < 30 min",
                "team": ["SOC", "Dev / AppSec", "Network"],
                "detectionMethods": ["WAF — Web Application Firewall", "SIEM", "Logs de aplicação", "RASP — Runtime Application Self-Protection"],
                "priority": "P2",
                "attack": [{"id": "T1190", "name": "Exploit Public-Facing Application"}],
                "related": ["api-compromise", "cloud-misconfig"],
                "objective": "Bloquear a exploração ativa de vulnerabilidades em aplicações web, corrigir a falha no código e assegurar que dados comprometidos na base de dados são identificados e limpos.",
                "indicators": ["Alertas de WAF para padrões de SQLi/XSS", "Erros de base de dados anómalos nos logs da aplicação",
                               "Parâmetros de URL/formulário com payloads suspeitos", "Alterações inesperadas de conteúdo em páginas (defacement)"],
                "containment": [
                    s("Bloquear os IPs atacantes e o padrão de payload via WAF", ["Cloudflare WAF, AWS WAF, F5 Advanced WAF, ModSecurity"]),
                    s("Colocar a aplicação/endpoint vulnerável em modo de manutenção se a exploração for ativa e severa", ["Load balancer / API Gateway — maintenance mode"]),
                    s("Reforçar regras do WAF para o tipo específico de injeção detetado", ["WAF — custom rule / virtual patching"]),
                ],
                "eradication": [
                    s("Corrigir a vulnerabilidade no código (parametrização de queries, sanitização/encoding de output)", ["SAST (SonarQube, Checkmarx)", "Code review + CI/CD gate"]),
                    s("Rever todo o código para instâncias semelhantes da mesma classe de vulnerabilidade", ["SAST/DAST (OWASP ZAP, Burp Suite, Snyk Code)"]),
                    s("Limpar registos maliciosos inseridos na base de dados (scripts XSS armazenados, dados alterados)", ["Ferramenta de administração de BD (SSMS, pgAdmin) + script de limpeza validado"]),
                ],
                "recovery": [
                    s("Validar a correção em ambiente de teste antes de repor em produção", ["Pipeline CI/CD com DAST automatizado"]),
                    s("Restaurar a partir de backup limpo se a integridade dos dados estiver comprometida", ["Backup de base de dados (point-in-time recovery)"]),
                ],
                "communication": [
                    s("Informar o dono da aplicação e a equipa de desenvolvimento"),
                    s("Avaliar se dados de clientes foram expostos e necessidade de notificação", ["Jurídico/DPO — avaliação RGPD"]),
                ],
                "postIncident": [
                    s("Incluir o caso em testes de segurança aplicacional (SAST/DAST) contínuos", ["Integração SAST/DAST no pipeline CI/CD"]),
                    s("Reforçar formação de secure coding para a equipa de desenvolvimento", ["OWASP Top 10 training / Secure Code Warrior"]),
                ],
            },
            {
                "id": "cloud-misconfig", "icon": "cloud", "name": "Configuração Incorreta em Nuvem", "severity": "high",
                "sla": "Ativação < 30 min",
                "team": ["Cloud Ops / DevOps", "SOC", "Segurança Cloud", "Network"],
                "detectionMethods": ["CSPM — Cloud Security Posture Management", "CloudTrail / Activity Logs", "Alertas nativos do provedor cloud"],
                "priority": "P2",
                "attack": [{"id": "T1530", "name": "Data from Cloud Storage"}, {"id": "T1580", "name": "Cloud Infrastructure Discovery"}],
                "related": ["exfiltracao", "api-compromise", "criptojacking"],
                "objective": "Corrigir rapidamente exposições causadas por má configuração na nuvem (ex: armazenamento público, permissões excessivas) e avaliar se houve acesso não autorizado enquanto a falha esteve ativa.",
                "indicators": ["Alertas de ferramentas CSPM (Cloud Security Posture Management)", "Buckets/contentores de armazenamento com acesso público",
                               "Políticas IAM com permissões excessivas (wildcard *)", "Acessos anómalos nos logs CloudTrail/Activity Log"],
                "containment": [
                    s("Corrigir imediatamente a permissão insegura (tornar bucket privado, remover acesso público)",
                      ["AWS Console/CLI (aws s3api put-public-access-block)", "Azure Portal/CLI (az storage blob service-properties)", "GCP (gcloud storage buckets)"]),
                    s("Restringir a política IAM afetada ao mínimo necessário", ["AWS IAM Access Analyzer", "Azure Entra ID PIM", "GCP IAM Recommender"]),
                    s("Rotacionar chaves de acesso que possam ter sido expostas", ["AWS IAM (rotate access keys)", "Azure Key Vault", "GCP Secret Manager"]),
                ],
                "eradication": [
                    s("Auditar os logs do CloudTrail/Activity Log para identificar acessos durante a exposição",
                      ["AWS CloudTrail + Athena", "Azure Activity Log + Sentinel", "GCP Cloud Audit Logs + BigQuery"]),
                    s("Verificar se dados foram descarregados ou modificados durante o período de exposição", ["Object storage access logs (S3 Server Access Logging)"]),
                    s("Identificar como/quando a configuração incorreta foi introduzida (IaC, alteração manual)", ["Terraform/CloudFormation state history", "Git blame no repositório de IaC"]),
                ],
                "recovery": [
                    s("Validar todas as configurações semelhantes no restante ambiente cloud", ["CSPM (Microsoft Defender for Cloud, Wiz, Prisma Cloud)"]),
                    s("Reimplementar via Infrastructure as Code com revisão obrigatória", ["Terraform/Pulumi + pull request review + tfsec/Checkov"]),
                ],
                "communication": [
                    s("RGPD: avaliar necessidade de notificação à CNPD (72h) se dados pessoais estiveram expostos publicamente"),
                    s("NIS2: registar o evento no processo de gestão de incidentes; escalar ao CNCS se causar indisponibilidade de serviço essencial"),
                    s("Informar a equipa de cloud/DevOps responsável pelo recurso"),
                ],
                "postIncident": [
                    s("Ativar CSPM com alertas automáticos e remediação automática (guardrails)", ["Microsoft Defender for Cloud, Wiz, Prisma Cloud — auto-remediation"]),
                    s("Implementar revisão obrigatória de infraestrutura como código antes de deploy", ["tfsec, Checkov, terraform plan gate em CI/CD"]),
                ],
            },
            {
                "id": "api-compromise", "icon": "terminal", "name": "Comprometimento de API", "severity": "high",
                "sla": "Ativação < 20 min",
                "team": ["SOC", "API / Platform Team", "Network"],
                "detectionMethods": ["API Gateway monitoring", "SIEM", "Secret scanning (repositórios de código)"],
                "priority": "P2",
                "attack": [{"id": "T1552", "name": "Unsecured Credentials"}, {"id": "T1078.004", "name": "Cloud Accounts"}],
                "related": ["cloud-misconfig", "web-attacks"],
                "objective": "Revogar imediatamente credenciais de API comprometidas, limitar o abuso através de rate limiting e restaurar o serviço com chaves seguras.",
                "indicators": ["Chamadas anómalas de volume ou padrão a partir de um token específico", "Uso da API fora de horário ou geografia habitual do cliente",
                               "Chaves de API encontradas expostas em repositórios públicos", "Erros de autenticação/autorização em massa"],
                "containment": [
                    s("Revogar instantaneamente as chaves de API afetadas", ["API Gateway (Kong, Azure APIM, AWS API Gateway) — revoke key"]),
                    s("Aplicar rate limiting agressivo por token/cliente durante a investigação", ["API Gateway — throttling policy"]),
                    s("Bloquear os IPs de origem das chamadas anómalas", ["WAF / NGFW"]),
                ],
                "eradication": [
                    s("Analisar as chamadas realizadas com a chave comprometida para determinar o impacto", ["API Gateway logs + SIEM"]),
                    s("Identificar a origem da exposição (código-fonte público, log, endpoint sem TLS)", ["Secret scanning (GitGuardian, TruffleHog, GitHub Advanced Security)"]),
                    s("Corrigir a causa raiz da exposição", ["Remoção de segredo do histórico Git (BFG Repo-Cleaner) + rotação"]),
                ],
                "recovery": [
                    s("Emitir novas chaves de API com escopo mínimo necessário", ["API Gateway — scoped API keys / OAuth scopes"]),
                    s("Comunicar ao cliente/integrador a necessidade de rotação da credencial"),
                ],
                "communication": [
                    s("Notificar clientes/parceiros integradores afetados sobre a rotação obrigatória"),
                    s("Documentar o incidente para a equipa de plataforma/API"),
                ],
                "postIncident": [
                    s("Implementar deteção de segredos em repositórios (secret scanning) no pipeline CI/CD", ["GitHub Advanced Security, GitGuardian, TruffleHog no CI/CD"]),
                    s("Reforçar expiração automática e scopes granulares para chaves de API", ["API Gateway — TTL automático + OAuth 2.0 scopes"]),
                ],
            },
        ],
    },
    {
        "id": "insider", "name": "Ameaças Internas e Ativos Físicos", "color": "var(--cat-insider)", "icon": "user-x",
        "playbooks": [
            {
                "id": "insider-threat", "icon": "user-x", "name": "Insider Threat (Ameaça Interna)", "severity": "critical",
                "sla": "Ativação < 1h (discreta)",
                "team": ["SOC", "RH", "Jurídico", "DPO", "Network"],
                "detectionMethods": ["UEBA — User Entity Behavior Analytics", "DLP", "Monitorização de acessos privilegiados (PAM)"],
                "priority": "P1",
                "attack": [{"id": "T1074", "name": "Data Staged"}, {"id": "T1005", "name": "Data from Local System"}, {"id": "T1078", "name": "Valid Accounts"}],
                "related": ["exfiltracao", "device-loss"],
                "objective": "Investigar e conter atividade maliciosa ou negligente de um colaborador com acesso legítimo, preservando evidência de forma discreta e em coordenação com RH e jurídico.",
                "indicators": ["Acesso a dados fora do âmbito da função", "Descarregamento massivo de ficheiros antes de saída da empresa",
                               "Uso de dispositivos de armazenamento não autorizados", "Tentativas de contornar controlos de segurança (DLP, proxy)"],
                "containment": [
                    s("Iniciar monitorização discreta da atividade do colaborador sem alertar o suspeito", ["UEBA (Microsoft Defender for Cloud Apps, Exabeam, Securonix)"]),
                    s("Validar com jurídico/DPO a base legal e a proporcionalidade da monitorização (RGPD e Código do Trabalho) antes de recolher evidência"),
                    s("Envolver RH e jurídico antes de qualquer ação visível sobre a conta"),
                    s("Preparar revogação de acessos para execução imediata no momento apropriado (ex: durante reunião com RH)", ["PAM/IAM — script de revogação pronto a executar"]),
                ],
                "eradication": [
                    s("Revogar todos os privilégios de acesso físico e lógico no momento definido em conjunto com RH/Legal",
                      ["Active Directory / Entra ID — disable account", "Controlo de acessos físicos (HID, Lenel) — desativar crachá"]),
                    s("Recolher e preservar provas (logs, emails, ficheiros) seguindo cadeia de custódia", ["Forense (Velociraptor, EnCase, FTK)", "eDiscovery (Microsoft Purview eDiscovery)"]),
                    s("Recuperar ativos da empresa (equipamento, crachás, credenciais)"),
                ],
                "recovery": [
                    s("Rever acessos de colegas próximos/subordinados que possam ter sido afetados", ["IAM — access review"]),
                    s("Restaurar dados eventualmente apagados ou corrompidos", ["Backup (Veeam, Microsoft 365 Backup)"]),
                ],
                "communication": [
                    s("Manter o círculo de conhecimento estritamente limitado (need-to-know)"),
                    s("Coordenar comunicação oficial com RH, jurídico e, se necessário, autoridades"),
                ],
                "postIncident": [
                    s("Rever processo de offboarding e revogação automática de acessos", ["IAM automation (Entra ID Lifecycle Workflows, SailPoint)"]),
                    s("Reforçar monitorização de comportamento anómalo (UEBA) para utilizadores privilegiados", ["UEBA + PAM session recording (CyberArk, BeyondTrust)"]),
                ],
            },
            {
                "id": "device-loss", "icon": "smartphone-off", "name": "Perda ou Roubo de Dispositivos", "severity": "medium",
                "sla": "Ativação < 30 min",
                "team": ["Helpdesk / IT", "Segurança Física", "Network"],
                "detectionMethods": ["Comunicação direta do colaborador", "MDM/EMM — alertas de geofencing", "Ausência de check-in do dispositivo"],
                "priority": "P3",
                "attack": [],
                "attackNote": "Não mapeado no MITRE ATT&CK Enterprise (risco de ativo físico) — ver ISO/IEC 27001 A.7 (Ativos)",
                "related": ["insider-threat", "credenciais"],
                "objective": "Impedir o acesso a dados corporativos num dispositivo perdido ou roubado através de bloqueio remoto, limpeza de dados e revogação de credenciais associadas.",
                "indicators": ["Comunicação do colaborador sobre perda/roubo", "Dispositivo fora da geofence habitual (MDM)",
                               "Ausência de check-in do dispositivo por período prolongado"],
                "containment": [
                    s("Bloquear remotamente o equipamento via MDM/EMM assim que reportado", ["Microsoft Intune, Jamf, VMware Workspace ONE — remote lock"]),
                    s("Revogar tokens de sessão e certificados digitais associados ao dispositivo", ["Entra ID — revoke device", "PKI interna — revogação de certificado"]),
                    s("Desativar temporariamente as contas com sessão ativa no dispositivo", ["Entra ID / Google Workspace — suspend sessions"]),
                ],
                "eradication": [
                    s("Executar limpeza remota de dados (remote wipe) se o dispositivo não for recuperado em prazo definido", ["Intune / Jamf / Workspace ONE — remote wipe"]),
                    s("Confirmar que a encriptação de disco estava ativa antes do incidente", ["BitLocker (Windows) / FileVault (macOS) — status via MDM"]),
                ],
                "recovery": [
                    s("Emitir novo dispositivo e certificados ao colaborador", ["MDM — enrolment automático (Autopilot/ABM)"]),
                    s("Restaurar acesso normal às contas após reconfiguração segura"),
                ],
                "communication": [
                    s("Registar boletim de ocorrência se se tratar de roubo"),
                    s("Avaliar se dados pessoais/sensíveis estavam armazenados localmente para efeitos de notificação RGPD"),
                ],
                "postIncident": [
                    s("Reforçar política de encriptação obrigatória de disco em todos os dispositivos", ["MDM — compliance policy (BitLocker/FileVault obrigatório)"]),
                    s("Rever tempo de resposta do processo de bloqueio/wipe remoto"),
                ],
            },
        ],
    },
]
